import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar/navbar";
import { Footer } from "./Components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PHP Hospital",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
