import Navbar from './(navbar)/page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PHP Hospital',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={inter.className}>
        <Navbar></Navbar>
        {/* Welcome Text */}
        <h1 className='bg-base-100 text-center py-2 text-xl'>Welcome to PHP Hospital,Bangladesh</h1>
        <hr></hr>
        {children}
      </body>
    </html>
  )
}
